server:
  port:
    8085
spring:
  datasource:
    username: root
    password: cql692932
    url: jdbc:mysql://localhost:3306/student?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

    filters: stat,wall,log4j